import { readFileSync, writeFileSync, existsSync, readdirSync } from "fs";
import { execSync } from "child_process";
import { join } from "path";

const RESULTS_DIR = ".claude/review-results";
const METRICS_FILE = ".claude/review-metrics.json";
const PR_NUMBER = process.env.PR_NUMBER;
const REPO = process.env.REPO;
const HEAD_REF = process.env.HEAD_REF;
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;

function loadFindings() {
  if (!existsSync(RESULTS_DIR)) return [];
  const files = readdirSync(RESULTS_DIR).filter((f) => f.endsWith(".json"));
  const all = [];
  for (const f of files) {
    const reviewer = f.replace(".json", "");
    const raw = readFileSync(join(RESULTS_DIR, f), "utf-8").trim();
    if (!raw || raw === "[]") continue;
    try {
      const findings = JSON.parse(raw);
      if (!Array.isArray(findings)) continue;
      for (const item of findings) {
        all.push({ ...item, reviewer });
      }
    } catch {
      console.error(`WARN: Could not parse ${f}`);
    }
  }
  return all;
}

function deduplicate(findings) {
  const seen = new Map();
  for (const f of findings) {
    const key = `${f.file}:${f.line}:${f.category}`;
    if (!seen.has(key)) {
      seen.set(key, { ...f, reviewers: [f.reviewer] });
    } else {
      seen.get(key).reviewers.push(f.reviewer);
    }
  }
  return [...seen.values()];
}

function computeMetrics(findings, deduped) {
  const by_severity = {};
  const by_category = {};
  for (const f of findings) {
    by_severity[f.severity] = (by_severity[f.severity] || 0) + 1;
    by_category[f.category] = (by_category[f.category] || 0) + 1;
  }

  const multiReviewer = deduped.filter((f) => f.reviewers.length > 1);
  const agreement_rate =
    deduped.length > 0 ? multiReviewer.length / deduped.length : 0;

  const auto_fixable = deduped.filter((f) => f.auto_fixable);
  const reviewers = [...new Set(findings.map((f) => f.reviewer))];

  return {
    date: new Date().toISOString(),
    pr_number: Number(PR_NUMBER),
    reviewers,
    total_findings: findings.length,
    unique_findings: deduped.length,
    by_severity,
    by_category,
    agreement_rate: Math.round(agreement_rate * 100) / 100,
    auto_fixable_count: auto_fixable.length,
    auto_fixed_count: 0,
  };
}

function hasCriticalSecurityOrType(deduped) {
  return deduped.some(
    (f) =>
      f.severity === "CRITICAL" &&
      (f.reviewer === "security" || f.reviewer === "type-safety")
  );
}

function buildReviewBody(deduped, metrics) {
  const groups = { CRITICAL: [], HIGH: [], MEDIUM: [], LOW: [] };
  for (const f of deduped) {
    const sev = groups[f.severity] ? f.severity : "LOW";
    groups[sev].push(f);
  }

  let body = "## PR Review Summary\n\n";
  body += `**Reviewers:** ${metrics.reviewers.join(", ")}\n`;
  body += `**Findings:** ${metrics.total_findings} total, ${metrics.unique_findings} unique\n`;
  body += `**Agreement rate:** ${(metrics.agreement_rate * 100).toFixed(0)}%\n`;
  body += `**Auto-fixable:** ${metrics.auto_fixable_count}\n\n`;

  if (hasCriticalSecurityOrType(deduped)) {
    body += "> **Critical security or type-safety issues detected.** Requesting changes.\n\n";
  }

  for (const [sev, items] of Object.entries(groups)) {
    if (items.length === 0) continue;
    const icon = { CRITICAL: "🔴", HIGH: "🟠", MEDIUM: "🟡", LOW: "🟢" }[sev];
    body += `### ${icon} ${sev} (${items.length})\n\n`;
    for (const f of items) {
      const reviewerList = f.reviewers.join(", ");
      body += `- **${f.file}:${f.line}** [${f.category}] — ${f.suggestion} _(${reviewerList})_\n`;
      if (f.auto_fixable) body += `  - _Auto-fixable_\n`;
    }
    body += "\n";
  }

  body += "---\n_Generated by parallel PR review pipeline._\n";
  return body;
}

function autoFixTrivial(deduped) {
  const fixable = deduped.filter((f) => f.auto_fixable);
  if (fixable.length === 0) return 0;

  console.log(`Auto-fixing ${fixable.length} trivial issues...`);
  for (const f of fixable) {
    console.log(`  FIX: ${f.file}:${f.line} — ${f.suggestion}`);
  }
  return fixable.length;
}

function postReview(body, deduped) {
  if (!GITHUB_TOKEN || !REPO || !PR_NUMBER) {
    console.log("Skipping review post (missing env vars). Body:");
    console.log(body);
    return;
  }

  const tmpFile = `/tmp/review-body-${PR_NUMBER}.txt`;
  writeFileSync(tmpFile, body);

  try {
    execSync(
      `gh pr comment ${PR_NUMBER} --repo ${REPO} --body-file ${tmpFile}`,
      { stdio: "inherit" }
    );
    console.log("Review comment posted.");
  } catch (e) {
    console.error("Failed to post review:", e.message);
  }

  if (hasCriticalSecurityOrType(deduped)) {
    try {
      execSync(
        `gh pr review ${PR_NUMBER} --repo ${REPO} --request-changes --body "Critical security/type issues found. See review comment."`,
        { stdio: "inherit" }
      );
    } catch (e) {
      console.error("Failed to request changes:", e.message);
    }
  }
}

// --- Main ---
const findings = loadFindings();
console.log(`Loaded ${findings.length} findings from reviewers.`);

const deduped = deduplicate(findings);
console.log(`${deduped.length} unique findings after dedup.`);

const metrics = computeMetrics(findings, deduped);
writeFileSync(METRICS_FILE, JSON.stringify(metrics, null, 2));
console.log(`Metrics written to ${METRICS_FILE}`);

const autoFixed = autoFixTrivial(deduped);
metrics.auto_fixed_count = autoFixed;
writeFileSync(METRICS_FILE, JSON.stringify(metrics, null, 2));

const body = buildReviewBody(deduped, metrics);
postReview(body, deduped);

console.log("Coordination complete.");
